---
repos:
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v4.3.21
      hooks:
          - id: isort
    - repo: https://github.com/python/black
      rev: 19.3b0
      hooks:
          - id: black
            language_version: python3.8
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.7.8
      hooks:
          - id: flake8
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.2.3
      hooks:
          - id: end-of-file-fixer
            files: '^.*\.(py|conf)$'
          - id: file-contents-sorter
            files: '^requirements(-test)?.in$'
