[tool.black]
skip-string-normalization = true
target_version = ['py38']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | \.vscode
    | \.circleci
    | \.test-reports
  )/
  | (.*)snap_(.*)
)
'''
